#!/usr/bin/env bash
# DEPRECATED: This file is replaced by generate-manifest.js (Node.js).
# The hooks.json now points to the .js version. This file is kept for one release
# cycle and will be removed in a future version.
#
# clarity-loop/hooks/generate-manifest.sh
# PostToolUse hook: regenerates docs/system/.manifest.md when system docs change.
# Also callable directly with --init flag from init.sh.
#
# Reads tool input from stdin (JSON) to detect if a system doc was modified.
# Parses ## headings with line ranges, detects cross-references, computes SHA-256.
# Output: docs/system/.manifest.md (~2-5KB)

set -euo pipefail

# --- Determine if we should run ---

# If called with --init, always run (from init.sh)
FORCE_RUN=false
if [ "${1:-}" = "--init" ]; then
  FORCE_RUN=true
fi

# Resolve project root
PROJECT_ROOT="${CLARITY_LOOP_PROJECT_ROOT:-$(pwd)}"
SYSTEM_DIR="$PROJECT_ROOT/docs/system"
MANIFEST="$SYSTEM_DIR/.manifest.md"

if [ "$FORCE_RUN" = false ]; then
  # Read hook input from stdin to check if a system doc was edited
  input=$(cat)

  file_path=$(echo "$input" | python3 -c "
import sys, json
data = json.load(sys.stdin)
tool_input = data.get('tool_input', {})
print(tool_input.get('file_path', ''))
" 2>/dev/null || echo "")

  # Only regenerate if the edited file is in docs/system/
  if ! echo "$file_path" | grep -q 'docs/system/'; then
    exit 0
  fi

  # Skip if the edited file IS the manifest
  if echo "$file_path" | grep -q 'docs/system/\.manifest\.md'; then
    exit 0
  fi
fi

# --- Check for system docs ---

if [ ! -d "$SYSTEM_DIR" ]; then
  exit 0
fi

# Find all .md files (excluding .manifest.md)
md_files=()
while IFS= read -r -d '' f; do
  md_files+=("$f")
done < <(find "$SYSTEM_DIR" -maxdepth 2 -name '*.md' ! -name '.manifest.md' -print0 2>/dev/null | sort -z)

if [ ${#md_files[@]} -eq 0 ]; then
  exit 0
fi

# --- Generate manifest ---

timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Compute combined content hash
combined_hash=$(cat "${md_files[@]}" | shasum -a 256 | cut -d' ' -f1)

# Start building manifest content
manifest_content="# System Doc Manifest

> Auto-generated by Clarity Loop. Do not edit manually.
> **Generated**: $timestamp
> **Content hash**: \`${combined_hash:0:16}\`
> **Documents**: ${#md_files[@]}

---

## Documents

| File | Lines | Sections | Last Modified |
|------|-------|----------|---------------|
"

# --- Per-file processing ---

section_index=""
cross_refs=""

for filepath in "${md_files[@]}"; do
  filename=$(basename "$filepath")
  relpath="${filepath#$SYSTEM_DIR/}"
  line_count=$(wc -l < "$filepath" | tr -d ' ')
  last_modified=$(stat -f "%Sm" -t "%Y-%m-%d" "$filepath" 2>/dev/null || date -r "$filepath" +"%Y-%m-%d" 2>/dev/null || echo "unknown")

  # Count ## headings (sections)
  section_count=$(grep -c '^##' "$filepath" 2>/dev/null || echo "0")

  manifest_content+="| $filename | $line_count | $section_count | $last_modified |
"

  # --- Build section index for this file ---
  section_index+="
### $filename
"

  # Parse ## headings with line numbers
  line_num=0
  prev_heading=""
  prev_line=0

  while IFS= read -r line; do
    line_num=$((line_num + 1))
    if echo "$line" | grep -qE '^#{1,4} '; then
      if [ -n "$prev_heading" ]; then
        end_line=$((line_num - 1))
        section_index+="- $prev_heading (lines $prev_line-$end_line)
"
      fi
      prev_heading="$line"
      prev_line=$line_num
    fi
  done < "$filepath"

  # Last heading runs to end of file
  if [ -n "$prev_heading" ]; then
    section_index+="- $prev_heading (lines $prev_line-$line_count)
"
  fi

  # --- Detect cross-references ---
  for other_file in "${md_files[@]}"; do
    other_name=$(basename "$other_file")
    if [ "$other_name" != "$filename" ]; then
      if grep -qF "$other_name" "$filepath" 2>/dev/null; then
        cross_refs+="- $filename -> $other_name
"
      fi
    fi
  done
done

# Assemble final manifest
manifest_content+="
---

## Section Index
$section_index
---

## Cross-References
"

if [ -n "$cross_refs" ]; then
  manifest_content+="$cross_refs"
else
  manifest_content+="No cross-references detected.
"
fi

# Write the manifest
echo "$manifest_content" > "$MANIFEST"
